# Generated by scripts/generate.py. Do not edit.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class ErrorEnvelopeError(TypedDict):
    code: str
    details: NotRequired[dict[str, Any]]
    message: str
    request_id: str
    retryable: bool


class HashtagMetrics(TypedDict):
    posts: int | None
    views: int | None


class MusicMetrics(TypedDict):
    posts: int | None


class SuccessEnvelopeMeta(TypedDict):
    cursors: SuccessEnvelopeMetaCursors


class SuccessEnvelopeMetaCursors(TypedDict):
    next: str | None


class TrendingCategoryMetrics(TypedDict):
    posts: int | None
    views: int | None


class TwitterListMetrics(TypedDict):
    followers: int | None
    members: int | None


Comment: TypeAlias = "CommentCore"


class CommentCore(TypedDict):
    author: PostAuthor
    id: str
    is_liked_by_post_author: bool | None
    is_pinned: bool | None
    media: list[PostMedia]
    metrics: CommentMetrics
    parent_id: str | None
    pinned_position: int | None
    published_at: str
    reply_preview: NotRequired[list[Comment]]
    text: str
    thread_root_id: str | None


class CommentMetrics(TypedDict):
    bookmarks: int | None
    likes: int | None
    quotes: int | None
    replies: int | None
    reposts: int | None
    views: int | None


Entity: TypeAlias = "EntityCore"


class EntityCore(TypedDict):
    attributes: dict[str, Any]
    description: str | None
    handle: str | None
    id: str
    image: MediaReference | None
    kind: str
    metrics: dict[str, Any]
    name: str | None
    url: str | None


class EntityReference(TypedDict):
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    name: NotRequired[str]
    url: NotRequired[str]


class ErrorEnvelope(TypedDict):
    error: ErrorEnvelopeError


class Hashtag(TypedDict):
    description: str | None
    id: str
    image: MediaReference | None
    metrics: HashtagMetrics
    name: str


class InstagramClipMetadata(TypedDict):
    author: NotRequired[EntityReference]
    caption: NotRequired[str]
    duration: NotRequired[float]
    height: NotRequired[int]
    id: str
    media: list[PostMedia]
    music: NotRequired[PostMusic]
    play_count: NotRequired[int]
    published_at: NotRequired[str]
    title: NotRequired[str]
    view_count: NotRequired[int]
    width: NotRequired[int]


class InstagramComment(CommentCore, TypedDict):
    pass


class InstagramCommentMetadata(TypedDict):
    can_comment: NotRequired[bool]
    can_view_more: NotRequired[bool]
    comment_count: NotRequired[int]
    comments_disabled: NotRequired[bool]
    id: str
    preview_count: NotRequired[int]


class InstagramCommentModeration(TypedDict):
    id: str
    is_bullying: NotRequired[bool]
    is_offensive: NotRequired[bool]
    is_spam: NotRequired[bool]
    reasons: list[str]
    score: NotRequired[float]
    text: NotRequired[str]


class InstagramEntity(EntityCore, TypedDict):
    pass


class InstagramHighlight(TypedDict):
    cover: NotRequired[MediaReference]
    id: str
    item_count: NotRequired[int]
    items: list[InstagramStory]
    owner: NotRequired[EntityReference]
    title: NotRequired[str]


class InstagramLocationGuide(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    item_count: NotRequired[int]
    location: NotRequired[PostLocation]
    title: NotRequired[str]
    url: NotRequired[str]


class InstagramMusicStream(TypedDict):
    bitrate: NotRequired[int]
    duration: NotRequired[float]
    expires_at: NotRequired[str]
    id: str
    mime_type: NotRequired[str]
    page: NotRequired[int]
    url: NotRequired[str]


class InstagramOEmbed(TypedDict):
    author_name: NotRequired[str]
    author_url: NotRequired[str]
    height: NotRequired[int]
    html: NotRequired[str]
    id: str
    provider_name: NotRequired[str]
    provider_url: NotRequired[str]
    thumbnail: NotRequired[MediaReference]
    title: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]
    width: NotRequired[int]


class InstagramPlayCountBreakdown(TypedDict):
    facebook: int | None
    instagram: int | None


class PostCore(TypedDict):
    author: PostAuthor
    caption: str | None
    comments_disabled: bool | None
    format: Literal["post", "reel", "story"]
    hashtags: list[str]
    id: str
    media: list[PostMedia]
    mentions: list[str]
    published_at: str
    title: str | None
    type: Literal["text", "image", "video", "carousel"]
    url: str


class InstagramPost(PostCore, TypedDict):
    collaborators: list[PostAuthor] | None
    extended: NotRequired[InstagramPostExtended]
    is_ad: bool | None
    is_paid_partnership: bool | None
    location: PostLocation | None
    metrics: InstagramPostMetrics
    music: PostMusic | None
    shortcode: str | None
    sponsors: list[PostAuthor] | None
    tagged_users: list[PostAuthor] | None


class InstagramPostExtended(TypedDict):
    accessibility_caption: str | None
    like_counts_hidden: bool | None
    product_type: str | None


class InstagramPostInsight(TypedDict):
    average_watch_time: NotRequired[float]
    comments: NotRequired[int]
    follows: NotRequired[int]
    id: str
    impressions: NotRequired[int]
    interactions: NotRequired[int]
    likes: NotRequired[int]
    plays: NotRequired[int]
    profile_visits: NotRequired[int]
    reach: NotRequired[int]
    saves: NotRequired[int]
    shares: NotRequired[int]
    views: NotRequired[int]
    watch_time: NotRequired[float]


class PostMetrics(TypedDict):
    comments: int | None
    likes: int | None
    reposts: int | None
    saves: int | None
    shares: int | None
    views: int | None


class InstagramPostMetrics(PostMetrics, TypedDict):
    play_count_breakdown: NotRequired[InstagramPlayCountBreakdown | None]


class ProfileCore(TypedDict):
    account_type: Literal["page", "profile"] | None
    avatar: MediaReference | None
    bio: str
    category: str | None
    display_name: str
    external_url: str | None
    handle: str
    id: str
    is_business: bool
    is_private: bool
    is_verified: bool
    metrics: ProfileMetrics


class InstagramProfile(ProfileCore, TypedDict):
    extended: NotRequired[InstagramProfileExtended]


class InstagramProfileAbout(TypedDict):
    bio: NotRequired[str]
    category: NotRequired[str]
    country: NotRequired[str]
    display_name: NotRequired[str]
    external_url: NotRequired[str]
    former_username_count: NotRequired[int]
    handle: NotRequired[str]
    id: str
    is_business: NotRequired[bool]
    is_private: NotRequired[bool]
    is_verified: NotRequired[bool]
    joined_at: NotRequired[str]


class InstagramProfileExtended(TypedDict):
    account_type_code: int | None
    address_street: str | None
    bio_links: list[ProfileLink]
    business_contact_method: str | None
    city: str | None
    latitude: float | None
    longitude: float | None
    postal_code: str | None
    public_email: str | None
    public_phone_country_code: str | None
    public_phone_number: str | None


class InstagramProfileSummary(TypedDict):
    avatar: NotRequired[MediaReference]
    bio: NotRequired[str]
    category: NotRequired[str]
    display_name: NotRequired[str]
    followers: NotRequired[int]
    handle: NotRequired[str]
    id: str
    is_private: NotRequired[bool]
    is_verified: NotRequired[bool]
    url: NotRequired[str]


class InstagramSearchResult(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    metrics: NotRequired[SearchResultMetrics]
    title: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class InstagramStory(TypedDict):
    author: NotRequired[EntityReference]
    can_quick_reply: NotRequired[bool]
    can_reply: NotRequired[bool]
    can_reshare: NotRequired[bool]
    expires_at: NotRequired[str]
    hashtags: list[str]
    id: str
    links: list[StoryLink]
    locations: list[PostLocation]
    media: list[PostMedia]
    mentions: list[EntityReference]
    published_at: NotRequired[str]
    shortcode: NotRequired[str]
    stickers: list[StorySticker]
    type: NotRequired[Literal["image", "video"]]


class InstagramTemplate(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    duration: NotRequired[float]
    id: str
    media: list[PostMedia]
    name: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class Location(TypedDict):
    address: str | None
    category: str | None
    city: str | None
    country_code: str | None
    id: str
    latitude: float | None
    longitude: float | None
    name: str
    phone: str | None
    postal_code: str | None
    region: str | None
    website: str | None


class MediaReference(TypedDict):
    expires_at: NotRequired[str]
    url: str


class MessageEnvelope(TypedDict):
    message: str


class Money(TypedDict):
    amount: str
    currency: NotRequired[str]


class Music(TypedDict):
    album: str | None
    artist: PostMusicArtist | None
    artwork: MediaReference | None
    audio: MediaReference | None
    duration: float | None
    id: str
    is_commercial: bool | None
    is_explicit: bool | None
    is_original: bool | None
    metrics: MusicMetrics
    title: str


class PostAuthor(TypedDict):
    avatar: MediaReference | None
    display_name: str | None
    handle: str
    id: str
    is_verified: bool | None


class PostLocation(TypedDict):
    address: str | None
    category: str | None
    city: str | None
    country_code: str | None
    id: str | None
    latitude: float | None
    longitude: float | None
    name: str | None
    phone: str | None
    postal_code: str | None
    region: str | None
    website: str | None


class PostMedia(TypedDict):
    alt_text: NotRequired[str]
    duration: NotRequired[float]
    expires_at: NotRequired[str]
    height: NotRequired[int]
    id: NotRequired[str]
    thumbnail: NotRequired[MediaReference]
    type: Literal["image", "video"]
    url: str
    variants: NotRequired[list[PostMediaVariant]]
    width: NotRequired[int]


class PostMediaVariant(TypedDict):
    bitrate: NotRequired[int]
    expires_at: NotRequired[str]
    height: NotRequired[int]
    mime_type: NotRequired[str]
    role: NotRequired[str]
    url: str
    watermarked: NotRequired[bool]
    width: NotRequired[int]


class PostMusic(TypedDict):
    album: str | None
    artist: PostMusicArtist | None
    artwork: MediaReference | None
    audio: MediaReference | None
    duration: float | None
    id: str
    is_commercial: bool | None
    is_explicit: bool | None
    is_original: bool | None
    title: str | None


class PostMusicArtist(TypedDict):
    id: str | None
    name: str


Profile: TypeAlias = "ProfileCore"


class ProfileLink(TypedDict):
    title: str | None
    url: str


class ProfileMetrics(TypedDict):
    followers: int | None
    following: int | None
    posts: int | None


class SearchResultMetrics(TypedDict):
    comments: NotRequired[int]
    followers: NotRequired[int]
    likes: NotRequired[int]
    posts: NotRequired[int]
    shares: NotRequired[int]
    views: NotRequired[int]


class StoryLink(TypedDict):
    display_url: NotRequired[str]
    height: NotRequired[float]
    rotation: NotRequired[float]
    title: NotRequired[str]
    url: str
    width: NotRequired[float]
    x: NotRequired[float]
    y: NotRequired[float]


class StorySticker(TypedDict):
    height: NotRequired[float]
    id: NotRequired[str]
    link: NotRequired[StoryLink]
    rotation: NotRequired[float]
    type: NotRequired[str]
    width: NotRequired[float]
    x: NotRequired[float]
    y: NotRequired[float]


class SuccessEnvelope(TypedDict):
    captured_at: str
    data: Any
    meta: NotRequired[SuccessEnvelopeMeta]
    platform: Literal["instagram", "tiktok", "twitter"]
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    source: Literal["live", "cache"]


class TestDataCatalog(TypedDict):
    changeNotes: list[str]
    contentHash: str
    datasetVersion: str
    entries: list[TestDataEntry]
    mediaProvenanceUrl: str
    operations: list[TestDataOperation]
    synthetic: Literal[True]


class TestDataCatalogEnvelope(TypedDict):
    data: TestDataCatalog


class TestDataEntry(TypedDict):
    datasetVersion: str
    description: str
    expected: TestDataExpectedResult
    id: str
    inputs: dict[str, Any]
    label: str
    operationIds: list[str]
    platform: Literal["instagram", "tiktok", "twitter"]
    relationships: list[TestDataRelationship]
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    synthetic: Literal[True]
    traits: list[str]


class TestDataEntryEnvelope(TypedDict):
    data: TestDataEntry


class TestDataExpectedResult(TypedDict):
    errorCode: NotRequired[str]
    status: Literal[200, 403, 404]


class TestDataOperation(TypedDict):
    description: str
    id: str
    inputFields: list[str]
    locators: list[str]
    method: Literal["GET"]
    paginated: bool
    path: str
    platform: Literal["instagram", "tiktok", "twitter"]
    publicSchema: str
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    summary: str
    toolName: str


class TestDataRelationship(TypedDict):
    entryId: str
    type: str


class TikTokComment(CommentCore, TypedDict):
    pass


class TikTokEffect(TypedDict):
    created_at: NotRequired[str]
    description: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    is_commercial: NotRequired[bool]
    name: NotRequired[str]
    post_count: NotRequired[int]
    type: NotRequired[str]
    url: NotRequired[str]
    view_count: NotRequired[int]


class TikTokEntity(EntityCore, TypedDict):
    pass


class TikTokInsight(TypedDict):
    growth_rate: NotRequired[float]
    id: str
    keyword: NotRequired[str]
    period: NotRequired[str]
    post_count: NotRequired[int]
    rank: NotRequired[int]
    related_keywords: list[str]
    search_volume: NotRequired[int]
    title: NotRequired[str]
    trend: NotRequired[str]
    view_count: NotRequired[int]


class TikTokLiveRanking(TypedDict):
    id: str
    rank: NotRequired[int]
    score: NotRequired[int]
    user: NotRequired[EntityReference]


class TikTokLiveRoom(TypedDict):
    cover: NotRequired[MediaReference]
    ended_at: NotRequired[str]
    host: NotRequired[EntityReference]
    id: str
    like_count: NotRequired[int]
    product_count: NotRequired[int]
    started_at: NotRequired[str]
    status: NotRequired[str]
    title: NotRequired[str]
    url: NotRequired[str]
    viewer_count: NotRequired[int]


class TikTokOption(TypedDict):
    description: NotRequired[str]
    id: str
    is_selected: NotRequired[bool]
    label: NotRequired[str]
    position: NotRequired[int]
    value: NotRequired[str]


class TikTokPlaylist(TypedDict):
    cover: NotRequired[MediaReference]
    created_at: NotRequired[str]
    description: NotRequired[str]
    id: str
    name: NotRequired[str]
    owner: NotRequired[EntityReference]
    play_count: NotRequired[int]
    post_count: NotRequired[int]
    updated_at: NotRequired[str]
    url: NotRequired[str]


class TikTokPost(PostCore, TypedDict):
    collaborators: list[PostAuthor] | None
    extended: NotRequired[TikTokPostExtended]
    is_ad: bool | None
    is_paid_partnership: bool | None
    location: PostLocation | None
    metrics: TikTokPostMetrics
    music: PostMusic | None
    sponsors: list[PostAuthor] | None
    tagged_users: list[PostAuthor] | None


class TikTokPostExtended(TypedDict):
    ai_label_type: NotRequired[int | None]
    allows_duet: NotRequired[bool | None]
    allows_stitch: NotRequired[bool | None]
    is_ai_generated: NotRequired[bool | None]
    is_downloadable: NotRequired[bool | None]
    uses_promotional_music: NotRequired[bool | None]


class TikTokPostMetrics(PostMetrics, TypedDict):
    downloads: int | None


class TikTokProfile(ProfileCore, TypedDict):
    extended: NotRequired[TikTokProfileExtended]


class TikTokProfileExtended(TypedDict):
    has_commerce: bool | None
    is_pro_account: bool | None
    verification_label: str | None
    verification_type: int | None


class TikTokQRCode(TypedDict):
    expires_at: NotRequired[str]
    height: NotRequired[int]
    id: str
    image: NotRequired[MediaReference]
    url: NotRequired[str]
    width: NotRequired[int]


class TikTokSearchResult(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    metrics: NotRequired[SearchResultMetrics]
    title: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class TikTokShopCategory(TypedDict):
    id: str
    name: NotRequired[str]
    parent_id: NotRequired[str]
    product_count: NotRequired[int]


class TikTokShopProduct(TypedDict):
    description: NotRequired[str]
    discount: NotRequired[str]
    id: str
    images: list[MediaReference]
    name: NotRequired[str]
    original_price: NotRequired[Money]
    price: NotRequired[Money]
    rating: NotRequired[float]
    review_count: NotRequired[int]
    seller: NotRequired[EntityReference]
    sold: NotRequired[int]
    stock: NotRequired[int]
    url: NotRequired[str]


class TikTokShopReview(TypedDict):
    author: NotRequired[EntityReference]
    helpful: NotRequired[int]
    id: str
    images: list[MediaReference]
    published_at: NotRequired[str]
    rating: NotRequired[float]
    text: NotRequired[str]


class TikTokShopSeller(TypedDict):
    description: NotRequired[str]
    followers: NotRequired[int]
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    name: NotRequired[str]
    products: NotRequired[int]
    rating: NotRequired[float]
    region: NotRequired[str]
    sold: NotRequired[int]
    url: NotRequired[str]


class TikTokSuggestion(TypedDict):
    highlighted: NotRequired[str]
    id: str
    score: NotRequired[float]
    text: str
    type: NotRequired[str]
    user: NotRequired[EntityReference]


class TrendingCategory(TypedDict):
    description: str | None
    id: str
    metrics: TrendingCategoryMetrics
    name: str


class TwitterComment(CommentCore, TypedDict):
    pass


class TwitterEntity(EntityCore, TypedDict):
    pass


class TwitterList(TypedDict):
    created_at: str | None
    description: str | None
    id: str
    is_private: bool | None
    metrics: TwitterListMetrics
    name: str
    owner: PostAuthor | None


class TwitterPost(PostCore, TypedDict):
    extended: NotRequired[TwitterPostExtended]
    metrics: TwitterPostMetrics
    quoted_post: NotRequired[TwitterPost | None]
    reposted_post: NotRequired[TwitterPost | None]


class TwitterPostExtended(TypedDict):
    conversation_id: NotRequired[str | None]
    in_reply_to_post_id: NotRequired[str | None]
    in_reply_to_user_id: NotRequired[str | None]
    language: NotRequired[str | None]
    quoted_post_id: NotRequired[str | None]
    reposted_post_id: NotRequired[str | None]


class TwitterPostMetrics(PostMetrics, TypedDict):
    bookmarks: int | None
    quotes: int | None


class TwitterProfile(ProfileCore, TypedDict):
    extended: NotRequired[TwitterProfileExtended]


class TwitterProfileExtended(TypedDict):
    banner: MediaReference | None
    created_at: str | None
    likes: int | None
    location: str | None
    media: int | None
    pinned_post_ids: list[str]
    withheld_countries: list[str]


class TwitterSuggestion(TypedDict):
    highlighted: NotRequired[str]
    id: str
    score: NotRequired[float]
    text: str
    type: NotRequired[str]
    user: NotRequired[EntityReference]


# One of the concrete resources returned by a URL fetch.
FetchResource: TypeAlias = "InstagramProfile | InstagramPost | InstagramStory | InstagramHighlight | TikTokProfile | TikTokPost | TwitterProfile | TwitterPost"
