# Generated by scripts/generate.py. Do not edit.

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class ErrorEnvelopeError(TypedDict):
    code: str
    details: NotRequired[dict[str, Any]]
    message: str
    requestId: str
    retryable: bool


class HashtagMetrics(TypedDict):
    posts: int | None
    views: int | None


class MusicMetrics(TypedDict):
    posts: int | None


class SuccessEnvelopeMeta(TypedDict):
    cursors: SuccessEnvelopeMetaCursors


class SuccessEnvelopeMetaCursors(TypedDict):
    next: str | None


class TrendingCategoryMetrics(TypedDict):
    posts: int | None
    views: int | None


class TwitterListMetrics(TypedDict):
    followers: int | None
    members: int | None


Comment: TypeAlias = "CommentCore"


class CommentCore(TypedDict):
    author: PostAuthor
    id: str
    isLikedByPostAuthor: bool | None
    isPinned: bool | None
    media: list[PostMedia]
    metrics: CommentMetrics
    parentId: str | None
    pinnedPosition: int | None
    publishedAt: str
    replyPreview: NotRequired[list[Comment]]
    text: str
    threadRootId: str | None


class CommentMetrics(TypedDict):
    bookmarks: int | None
    likes: int | None
    quotes: int | None
    replies: int | None
    reposts: int | None
    views: int | None


Entity: TypeAlias = "EntityCore"


class EntityCore(TypedDict):
    attributes: dict[str, Any]
    description: str | None
    handle: str | None
    id: str
    image: MediaReference | None
    kind: str
    metrics: dict[str, Any]
    name: str | None
    url: str | None


class EntityReference(TypedDict):
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    name: NotRequired[str]
    url: NotRequired[str]


class ErrorEnvelope(TypedDict):
    error: ErrorEnvelopeError


class Hashtag(TypedDict):
    description: str | None
    id: str
    image: MediaReference | None
    metrics: HashtagMetrics
    name: str


class InstagramClipMetadata(TypedDict):
    author: NotRequired[EntityReference]
    caption: NotRequired[str]
    duration: NotRequired[float]
    height: NotRequired[int]
    id: str
    media: list[PostMedia]
    music: NotRequired[PostMusic]
    playCount: NotRequired[int]
    publishedAt: NotRequired[str]
    title: NotRequired[str]
    viewCount: NotRequired[int]
    width: NotRequired[int]


class InstagramComment(CommentCore, TypedDict):
    pass


class InstagramCommentMetadata(TypedDict):
    canComment: NotRequired[bool]
    canViewMore: NotRequired[bool]
    commentCount: NotRequired[int]
    commentsDisabled: NotRequired[bool]
    id: str
    previewCount: NotRequired[int]


class InstagramCommentModeration(TypedDict):
    id: str
    isBullying: NotRequired[bool]
    isOffensive: NotRequired[bool]
    isSpam: NotRequired[bool]
    reasons: list[str]
    score: NotRequired[float]
    text: NotRequired[str]


class InstagramEntity(EntityCore, TypedDict):
    pass


class InstagramHighlight(TypedDict):
    cover: NotRequired[MediaReference]
    id: str
    itemCount: NotRequired[int]
    items: list[InstagramStory]
    owner: NotRequired[EntityReference]
    title: NotRequired[str]


class InstagramLocationGuide(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    itemCount: NotRequired[int]
    location: NotRequired[PostLocation]
    title: NotRequired[str]
    url: NotRequired[str]


class InstagramMusicStream(TypedDict):
    bitrate: NotRequired[int]
    duration: NotRequired[float]
    expiresAt: NotRequired[str]
    id: str
    mimeType: NotRequired[str]
    page: NotRequired[int]
    url: NotRequired[str]


class InstagramOEmbed(TypedDict):
    authorName: NotRequired[str]
    authorUrl: NotRequired[str]
    height: NotRequired[int]
    html: NotRequired[str]
    id: str
    providerName: NotRequired[str]
    providerUrl: NotRequired[str]
    thumbnail: NotRequired[MediaReference]
    title: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]
    width: NotRequired[int]


class InstagramPlayCountBreakdown(TypedDict):
    facebook: int | None
    instagram: int | None


class PostCore(TypedDict):
    author: PostAuthor
    caption: str | None
    commentsDisabled: bool | None
    format: Literal["post", "reel", "story"]
    hashtags: list[str]
    id: str
    media: list[PostMedia]
    mentions: list[str]
    publishedAt: str
    title: str | None
    type: Literal["text", "image", "video", "carousel"]
    url: str


class InstagramPost(PostCore, TypedDict):
    collaborators: list[PostAuthor] | None
    extended: NotRequired[InstagramPostExtended]
    isAd: bool | None
    isPaidPartnership: bool | None
    location: PostLocation | None
    metrics: InstagramPostMetrics
    music: PostMusic | None
    shortcode: str | None
    sponsors: list[PostAuthor] | None
    taggedUsers: list[PostAuthor] | None


class InstagramPostExtended(TypedDict):
    accessibilityCaption: str | None
    likeCountsHidden: bool | None
    productType: str | None


class InstagramPostInsight(TypedDict):
    averageWatchTime: NotRequired[float]
    comments: NotRequired[int]
    follows: NotRequired[int]
    id: str
    impressions: NotRequired[int]
    interactions: NotRequired[int]
    likes: NotRequired[int]
    plays: NotRequired[int]
    profileVisits: NotRequired[int]
    reach: NotRequired[int]
    saves: NotRequired[int]
    shares: NotRequired[int]
    views: NotRequired[int]
    watchTime: NotRequired[float]


class PostMetrics(TypedDict):
    comments: int | None
    likes: int | None
    reposts: int | None
    saves: int | None
    shares: int | None
    views: int | None


class InstagramPostMetrics(PostMetrics, TypedDict):
    playCountBreakdown: NotRequired[InstagramPlayCountBreakdown | None]


class ProfileCore(TypedDict):
    accountType: Literal["page", "profile"] | None
    avatar: MediaReference | None
    bio: str
    category: str | None
    displayName: str
    externalUrl: str | None
    handle: str
    id: str
    isBusiness: bool
    isPrivate: bool
    isVerified: bool
    metrics: ProfileMetrics


class InstagramProfile(ProfileCore, TypedDict):
    extended: NotRequired[InstagramProfileExtended]


class InstagramProfileAbout(TypedDict):
    bio: NotRequired[str]
    category: NotRequired[str]
    country: NotRequired[str]
    displayName: NotRequired[str]
    externalUrl: NotRequired[str]
    formerUsernameCount: NotRequired[int]
    handle: NotRequired[str]
    id: str
    isBusiness: NotRequired[bool]
    isPrivate: NotRequired[bool]
    isVerified: NotRequired[bool]
    joinedAt: NotRequired[str]


class InstagramProfileExtended(TypedDict):
    accountTypeCode: int | None
    addressStreet: str | None
    bioLinks: list[ProfileLink]
    businessContactMethod: str | None
    city: str | None
    latitude: float | None
    longitude: float | None
    postalCode: str | None
    publicEmail: str | None
    publicPhoneCountryCode: str | None
    publicPhoneNumber: str | None


class InstagramProfileSummary(TypedDict):
    avatar: NotRequired[MediaReference]
    bio: NotRequired[str]
    category: NotRequired[str]
    displayName: NotRequired[str]
    followers: NotRequired[int]
    handle: NotRequired[str]
    id: str
    isPrivate: NotRequired[bool]
    isVerified: NotRequired[bool]
    url: NotRequired[str]


class InstagramSearchResult(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    handle: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    metrics: NotRequired[SearchResultMetrics]
    title: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class InstagramStory(TypedDict):
    author: NotRequired[EntityReference]
    canQuickReply: NotRequired[bool]
    canReply: NotRequired[bool]
    canReshare: NotRequired[bool]
    expiresAt: NotRequired[str]
    hashtags: list[str]
    id: str
    links: list[StoryLink]
    locations: list[PostLocation]
    media: list[PostMedia]
    mentions: list[EntityReference]
    publishedAt: NotRequired[str]
    shortcode: NotRequired[str]
    stickers: list[StorySticker]
    type: NotRequired[Literal["image", "video"]]


class InstagramTemplate(TypedDict):
    author: NotRequired[EntityReference]
    description: NotRequired[str]
    duration: NotRequired[float]
    id: str
    media: list[PostMedia]
    name: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class Location(TypedDict):
    address: str | None
    category: str | None
    city: str | None
    countryCode: str | None
    id: str
    latitude: float | None
    longitude: float | None
    name: str
    phone: str | None
    postalCode: str | None
    region: str | None
    website: str | None


class MediaReference(TypedDict):
    expiresAt: NotRequired[str]
    url: str


class MessageEnvelope(TypedDict):
    message: str


class Music(TypedDict):
    album: str | None
    artist: PostMusicArtist | None
    artwork: MediaReference | None
    audio: MediaReference | None
    duration: float | None
    id: str
    isCommercial: bool | None
    isExplicit: bool | None
    isOriginal: bool | None
    metrics: MusicMetrics
    title: str


class PostAuthor(TypedDict):
    avatar: MediaReference | None
    displayName: str | None
    handle: str
    id: str
    isVerified: bool | None


class PostLocation(TypedDict):
    address: str | None
    category: str | None
    city: str | None
    countryCode: str | None
    id: str | None
    latitude: float | None
    longitude: float | None
    name: str | None
    phone: str | None
    postalCode: str | None
    region: str | None
    website: str | None


class PostMedia(TypedDict):
    altText: NotRequired[str]
    duration: NotRequired[float]
    expiresAt: NotRequired[str]
    height: NotRequired[int]
    id: NotRequired[str]
    thumbnail: NotRequired[MediaReference]
    type: Literal["image", "video"]
    url: str
    variants: NotRequired[list[PostMediaVariant]]
    width: NotRequired[int]


class PostMediaVariant(TypedDict):
    bitrate: NotRequired[int]
    expiresAt: NotRequired[str]
    height: NotRequired[int]
    mimeType: NotRequired[str]
    role: NotRequired[str]
    url: str
    watermarked: NotRequired[bool]
    width: NotRequired[int]


class PostMusic(TypedDict):
    album: str | None
    artist: PostMusicArtist | None
    artwork: MediaReference | None
    audio: MediaReference | None
    duration: float | None
    id: str
    isCommercial: bool | None
    isExplicit: bool | None
    isOriginal: bool | None
    title: str | None


class PostMusicArtist(TypedDict):
    id: str | None
    name: str


Profile: TypeAlias = "ProfileCore"


class ProfileLink(TypedDict):
    title: str | None
    url: str


class ProfileMetrics(TypedDict):
    followers: int | None
    following: int | None
    posts: int | None


class SearchResultMetrics(TypedDict):
    comments: NotRequired[int]
    followers: NotRequired[int]
    likes: NotRequired[int]
    posts: NotRequired[int]
    shares: NotRequired[int]
    views: NotRequired[int]


class StoryLink(TypedDict):
    displayUrl: NotRequired[str]
    height: NotRequired[float]
    rotation: NotRequired[float]
    title: NotRequired[str]
    url: str
    width: NotRequired[float]
    x: NotRequired[float]
    y: NotRequired[float]


class StorySticker(TypedDict):
    height: NotRequired[float]
    id: NotRequired[str]
    link: NotRequired[StoryLink]
    rotation: NotRequired[float]
    type: NotRequired[str]
    width: NotRequired[float]
    x: NotRequired[float]
    y: NotRequired[float]


class SuccessEnvelope(TypedDict):
    capturedAt: str
    data: Any
    meta: NotRequired[SuccessEnvelopeMeta]
    platform: Literal["instagram", "tiktok", "twitter"]
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    source: Literal["live", "cache"]


class TestDataCatalog(TypedDict):
    changeNotes: list[str]
    contentHash: str
    datasetVersion: str
    entries: list[TestDataEntry]
    mediaProvenanceUrl: str
    operations: list[TestDataOperation]
    synthetic: Literal[True]


class TestDataCatalogEnvelope(TypedDict):
    data: TestDataCatalog


class TestDataEntry(TypedDict):
    datasetVersion: str
    description: str
    expected: TestDataExpectedResult
    id: str
    inputs: dict[str, Any]
    label: str
    operationIds: list[str]
    platform: Literal["instagram", "tiktok", "twitter"]
    relationships: list[TestDataRelationship]
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    synthetic: Literal[True]
    traits: list[str]


class TestDataEntryEnvelope(TypedDict):
    data: TestDataEntry


class TestDataExpectedResult(TypedDict):
    errorCode: NotRequired[str]
    status: Literal[200, 403, 404]


class TestDataOperation(TypedDict):
    description: str
    id: str
    inputFields: list[str]
    locators: list[str]
    method: Literal["GET"]
    paginated: bool
    path: str
    platform: Literal["instagram", "tiktok", "twitter"]
    publicSchema: str
    resource: Literal["profile", "post", "comment", "hashtag", "location", "music", "category", "list", "entity"]
    summary: str
    toolName: str


class TestDataRelationship(TypedDict):
    entryId: str
    type: str


class TikTokComment(CommentCore, TypedDict):
    pass


class TikTokEffect(TypedDict):
    createdAt: NotRequired[str]
    description: NotRequired[str]
    id: str
    image: NotRequired[MediaReference]
    isCommercial: NotRequired[bool]
    name: NotRequired[str]
    postCount: NotRequired[int]
    type: NotRequired[str]
    url: NotRequired[str]
    viewCount: NotRequired[int]


class TikTokEntity(EntityCore, TypedDict):
    pass


class TikTokPlaylist(TypedDict):
    cover: NotRequired[MediaReference]
    createdAt: NotRequired[str]
    description: NotRequired[str]
    id: str
    name: NotRequired[str]
    owner: NotRequired[EntityReference]
    playCount: NotRequired[int]
    postCount: NotRequired[int]
    updatedAt: NotRequired[str]
    url: NotRequired[str]


class TikTokPost(PostCore, TypedDict):
    collaborators: list[PostAuthor] | None
    extended: NotRequired[TikTokPostExtended]
    isAd: bool | None
    isPaidPartnership: bool | None
    location: PostLocation | None
    metrics: TikTokPostMetrics
    music: PostMusic | None
    sponsors: list[PostAuthor] | None
    taggedUsers: list[PostAuthor] | None


class TikTokPostExtended(TypedDict):
    aiLabelType: NotRequired[int | None]
    allowsDuet: NotRequired[bool | None]
    allowsStitch: NotRequired[bool | None]
    isAiGenerated: NotRequired[bool | None]
    isDownloadable: NotRequired[bool | None]
    usesPromotionalMusic: NotRequired[bool | None]


class TikTokPostMetrics(PostMetrics, TypedDict):
    downloads: int | None


class TikTokProfile(ProfileCore, TypedDict):
    extended: NotRequired[TikTokProfileExtended]


class TikTokProfileExtended(TypedDict):
    hasCommerce: bool | None
    isProAccount: bool | None
    verificationLabel: str | None
    verificationType: int | None


class TrendingCategory(TypedDict):
    description: str | None
    id: str
    metrics: TrendingCategoryMetrics
    name: str


class TwitterComment(CommentCore, TypedDict):
    pass


class TwitterEntity(EntityCore, TypedDict):
    pass


class TwitterList(TypedDict):
    createdAt: str | None
    description: str | None
    id: str
    isPrivate: bool | None
    metrics: TwitterListMetrics
    name: str
    owner: PostAuthor | None


class TwitterPost(PostCore, TypedDict):
    extended: NotRequired[TwitterPostExtended]
    metrics: TwitterPostMetrics
    quotedPost: NotRequired[TwitterPost | None]
    repostedPost: NotRequired[TwitterPost | None]


class TwitterPostExtended(TypedDict):
    conversationId: NotRequired[str | None]
    inReplyToPostId: NotRequired[str | None]
    inReplyToUserId: NotRequired[str | None]
    language: NotRequired[str | None]
    quotedPostId: NotRequired[str | None]
    repostedPostId: NotRequired[str | None]


class TwitterPostMetrics(PostMetrics, TypedDict):
    bookmarks: int | None
    quotes: int | None


class TwitterProfile(ProfileCore, TypedDict):
    extended: NotRequired[TwitterProfileExtended]


class TwitterProfileExtended(TypedDict):
    banner: MediaReference | None
    createdAt: str | None
    likes: int | None
    location: str | None
    media: int | None
    pinnedPostIds: list[str]
    withheldCountries: list[str]


class TwitterSuggestion(TypedDict):
    highlighted: NotRequired[str]
    id: str
    score: NotRequired[float]
    text: str
    type: NotRequired[str]
    user: NotRequired[EntityReference]


# One of the concrete resources returned by a URL fetch.
FetchResource: TypeAlias = "InstagramProfile | InstagramPost | InstagramStory | InstagramHighlight | TikTokProfile | TikTokPost | TwitterProfile | TwitterPost"
