#!/usr/bin/env python3
"""Generate the typed OpenHandle SDK sources from the pinned OpenAPI contract."""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path
from typing import Any, cast

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
GENERATED_HEADER = "# Generated by scripts/generate.py. Do not edit.\n\n"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
TERMINAL_OPERATIONS = ("fetch", "get", "list", "search")
INITIALISMS = {"id": "ID", "ids": "IDs", "oembed": "OEmbed", "qrCode": "QRCode", "tiktok": "TikTok", "url": "URL"}
CONTROL_PARAMETERS = "timeout: float | None = None, max_retries: int | None = None"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    parser.add_argument("--input", default=str(PACKAGE_ROOT / "openapi" / "openhandle.json"))
    arguments = parser.parse_args()

    document = json.loads(Path(arguments.input).read_text())
    generator = Generator(document)
    outputs = {
        "src/openhandle/models.py": generator.models(),
        "src/openhandle/_operations.py": generator.manifest(),
        "src/openhandle/_sync_resources.py": generator.resources(sync=True),
        "src/openhandle/_async_resources.py": generator.resources(sync=False),
    }
    for relative_path, contents in outputs.items():
        write_generated(relative_path, contents, check=arguments.check)


class Generator:
    def __init__(self, document: dict[str, Any]) -> None:
        self.schemas: dict[str, Any] = document.get("components", {}).get("schemas", {})
        self.operations = operation_definitions(document)
        self.auxiliary: dict[str, str] = {}

    # ------------------------------------------------------------------ models

    def models(self) -> str:
        declarations: list[str] = []
        for name in ordered_schema_names(self.schemas):
            declarations.append(self.model_declaration(name, self.schemas[name]))
        fetch_union = self.fetch_data_union()
        if fetch_union:
            declarations.append(
                "# One of the concrete resources returned by a URL fetch.\n"
                f'FetchResource: TypeAlias = "{fetch_union}"\n'
            )
        body = "\n\n".join(list(self.auxiliary.values()) + declarations)
        return (
            GENERATED_HEADER
            + "from __future__ import annotations\n\n"
            + "from typing import Any, Literal, TypeAlias\n\n"
            + "from typing_extensions import NotRequired, TypedDict\n\n\n"
            + body
        )

    def model_declaration(self, name: str, schema: dict[str, Any]) -> str:
        if set(schema) == {"$ref"}:
            return f'{name}: TypeAlias = "{reference_name(schema["$ref"])}"\n'
        if "allOf" in schema or schema_is_object(schema):
            return self.typed_dict(name, schema)
        return f"{name}: TypeAlias = {self.type_expression(schema, name, required=True)}\n"

    def typed_dict(self, name: str, schema: dict[str, Any]) -> str:
        bases, properties, required = self.flattened_members(schema, inherit=True)
        lines = [f"class {name}({', '.join([*bases, 'TypedDict'])}):"]
        if not properties:
            lines.append("    pass")
        for property_name in properties:
            if not property_name.isidentifier() or keyword.iskeyword(property_name):
                bases, properties, required = self.flattened_members(schema, inherit=False)
                return self.functional_typed_dict(name, properties, required)
        for property_name, property_schema in properties.items():
            expression = self.type_expression(property_schema, f"{name}{pascal_case(property_name)}", required=True)
            if property_name not in required:
                expression = f"NotRequired[{expression}]"
            lines.append(f"    {property_name}: {expression}")
        return "\n".join(lines) + "\n"

    def functional_typed_dict(self, name: str, properties: dict[str, Any], required: set[str]) -> str:
        fields = []
        for property_name, property_schema in properties.items():
            expression = self.type_expression(property_schema, f"{name}{pascal_case(property_name)}", required=True)
            if property_name not in required:
                expression = f"NotRequired[{expression}]"
            fields.append(f'        "{property_name}": {expression},')
        return f'{name} = TypedDict(\n    "{name}",\n    {{\n' + "\n".join(fields) + "\n    },\n)\n"

    def flattened_members(self, schema: dict[str, Any], *, inherit: bool) -> tuple[list[str], dict[str, Any], set[str]]:
        bases: list[str] = []
        properties: dict[str, Any] = {}
        required: set[str] = set()

        def merge(part: dict[str, Any], into_bases: bool) -> None:
            if "$ref" in part:
                name = reference_name(part["$ref"])
                if into_bases:
                    if name not in bases:
                        bases.append(name)
                    return
                merge(self.schemas[name], into_bases=False)
                return
            for sub_part in part.get("allOf", []):
                merge(sub_part, into_bases)
            properties.update(part.get("properties", {}))
            required.update(part.get("required", []))

        merge(schema, into_bases=inherit)
        if inherit and any(property_name in self.inherited_properties(bases) for property_name in properties):
            return self.flattened_members(schema, inherit=False)
        return bases, properties, required

    def inherited_properties(self, bases: list[str]) -> set[str]:
        names: set[str] = set()
        for base in bases:
            _, properties, _ = self.flattened_members(self.schemas[base], inherit=False)
            names.update(properties)
        return names

    def type_expression(self, schema: dict[str, Any], context: str, *, required: bool) -> str:
        if not schema:
            return "Any"
        if "$ref" in schema:
            return reference_name(schema["$ref"])
        if "anyOf" in schema or "oneOf" in schema:
            variants = schema.get("anyOf", []) + schema.get("oneOf", [])
            parts: list[str] = []
            nullable = False
            for variant in variants:
                if variant.get("type") == "null":
                    nullable = True
                    continue
                parts.append(self.type_expression(variant, context, required=True))
            expression = " | ".join(dict.fromkeys(parts)) or "Any"
            return f"{expression} | None" if nullable else expression
        if "allOf" in schema:
            if len(schema["allOf"]) == 1 and "$ref" in schema["allOf"][0]:
                return reference_name(schema["allOf"][0]["$ref"])
            return self.auxiliary_typed_dict(schema, context)
        types = schema.get("type")
        types = types if isinstance(types, list) else [types] if types else []
        nullable = "null" in types
        if "enum" in schema:
            literals = ", ".join(literal_value(value) for value in schema["enum"] if value is not None)
            expression = f"Literal[{literals}]"
            if None in schema["enum"] or nullable:
                expression += " | None"
            return expression
        if "const" in schema:
            return f"Literal[{literal_value(schema['const'])}]"
        if "array" in types:
            items = schema.get("items")
            expression = (
                f"list[{self.type_expression(items, f'{context}Item', required=True)}]" if items else "list[Any]"
            )
        elif "object" in types or "properties" in schema:
            if schema.get("properties"):
                expression = self.auxiliary_typed_dict(schema, context)
            else:
                expression = "dict[str, Any]"
        elif "integer" in types:
            expression = "int"
        elif "number" in types:
            expression = "float"
        elif "boolean" in types:
            expression = "bool"
        elif "string" in types:
            expression = "str"
        else:
            return "Any"
        return f"{expression} | None" if nullable else expression

    def auxiliary_typed_dict(self, schema: dict[str, Any], context: str) -> str:
        if context in self.schemas:
            raise SystemExit(f"generator: auxiliary model name {context} collides with a component schema.")
        if context not in self.auxiliary:
            self.auxiliary[context] = ""
            self.auxiliary[context] = self.typed_dict(context, schema)
        return context

    def fetch_data_union(self) -> str:
        for operation in self.operations:
            if operation["operation"] != "fetch":
                continue
            response = operation["definition"]["responses"]["200"]["content"]["application/json"]["schema"]
            references = []
            for variant in response.get("oneOf", []):
                data = self.find_property(variant, "data")
                if data and "$ref" in data:
                    name = reference_name(data["$ref"])
                    if name not in references:
                        references.append(name)
            return " | ".join(references)
        return ""

    def find_property(self, schema: dict[str, Any], name: str) -> dict[str, Any] | None:
        if "$ref" in schema:
            return self.find_property(self.schemas[reference_name(schema["$ref"])], name)
        if name in schema.get("properties", {}):
            return cast("dict[str, Any]", schema["properties"][name])
        for part in reversed(schema.get("allOf", [])):
            found = self.find_property(part, name)
            if found is not None:
                return found
        return None

    # ---------------------------------------------------------------- manifest

    def manifest(self) -> str:
        entries = []
        for operation in self.operations:
            scope = tuple(
                {key: value for key, value in segment.items() if key in ("name", "parameter", "reference")}
                for segment in operation["scope"]
            )
            entries.append(
                "    {\n"
                f'        "api_path": {operation["api_path"]!r},\n'
                f'        "method": {operation["method"]!r},\n'
                f'        "operation": {operation["operation"]!r},\n'
                f'        "paginated": {operation["paginated"]!r},\n'
                f'        "path": {operation["path"]!r},\n'
                f'        "scope": {scope!r},\n'
                "    },"
            )
        return (
            GENERATED_HEADER
            + "from __future__ import annotations\n\n"
            + "from typing import Any\n\n"
            + "OPERATIONS: tuple[dict[str, Any], ...] = (\n"
            + "\n".join(entries)
            + "\n)\n"
        )

    # --------------------------------------------------------------- resources

    def resources(self, *, sync: bool) -> str:
        root = TreeNode(path=[])
        for operation in self.operations:
            node = root
            for segment in operation["scope"]:
                child = node.children.get(segment["name"])
                if child is None:
                    child = TreeNode(path=[*node.path, segment["name"]], scope=segment)
                    node.children[segment["name"]] = child
                node = child
            node.operations[operation["operation"]] = operation

        classes: list[str] = []
        for child in self.ordered_nodes(root):
            classes.append(self.node_class(child, sync=sync))
        classes.append(self.root_class(root, sync=sync))

        page_type = "Page" if sync else "AsyncPage"
        transport_type = "SyncTransport" if sync else "AsyncTransport"
        iterator_import = "Iterator" if sync else "AsyncIterator"
        return (
            GENERATED_HEADER
            + "from __future__ import annotations\n\n"
            + f"from collections.abc import {iterator_import}\n"
            + "from datetime import datetime\n"
            + "from typing import Any, Literal\n\n"
            + "from openhandle import models\n"
            + "from openhandle._references import resolve_selector\n"
            + f"from openhandle._response import {page_type}, Response\n"
            + f"from openhandle._transport import {transport_type}\n"
            + "from openhandle._types import Freshness\n\n\n"
            + "\n\n\n".join(classes)
            + "\n"
        )

    def ordered_nodes(self, root: TreeNode) -> list[TreeNode]:
        result: list[TreeNode] = []

        def visit(node: TreeNode) -> None:
            for child in node.children.values():
                visit(child)
                result.append(child)

        visit(root)
        return result

    def node_class(self, node: TreeNode, *, sync: bool) -> str:
        class_name = node_class_name(node.path, sync=sync)
        transport_type = "SyncTransport" if sync else "AsyncTransport"
        lines = [f"class {class_name}:"]
        lines.append(f"    def __init__(self, transport: {transport_type}, bindings: dict[str, str]) -> None:")
        lines.append("        self._transport = transport")
        lines.append("        self._bindings = bindings")
        for name, child in node.children.items():
            if not child.scope.get("parameter"):
                lines.append(
                    f"        self.{accessor_name(name)} = {node_class_name(child.path, sync=sync)}(transport, bindings)"
                )
        body = ["\n".join(lines)]
        for name, child in node.children.items():
            if child.scope.get("parameter"):
                body.append(self.selector_method(node, name, child, sync=sync))
        for operation in node.operations.values():
            body.append(self.operation_method(node, operation, sync=sync))
            if operation["paginated"]:
                body.append(self.items_method(node, operation, sync=sync))
        return "\n\n".join(body)

    def root_class(self, root: TreeNode, *, sync: bool) -> str:
        class_name = "GeneratedClient" if sync else "AsyncGeneratedClient"
        transport_type = "SyncTransport" if sync else "AsyncTransport"
        lines = [f"class {class_name}:"]
        lines.append(f"    def __init__(self, transport: {transport_type}) -> None:")
        lines.append("        self._transport = transport")
        for name, child in root.children.items():
            lines.append(
                f"        self.{accessor_name(name)} = {node_class_name(child.path, sync=sync)}(transport, {{}})"
            )
        body = ["\n".join(lines)]
        for operation in root.operations.values():
            body.append(self.operation_method(root, operation, sync=sync))
        return "\n\n".join(body)

    def selector_method(self, node: TreeNode, name: str, child: TreeNode, *, sync: bool) -> str:
        family = child.scope.get("reference") or name
        platform = child.path[0]
        keywords = ["username", "id", "url"] if family == "profile" else ["id", "url"]
        keyword_parameters = "".join(f", {value}: str | None = None" for value in keywords)
        keyword_arguments = "".join(f", {value}={value}" for value in keywords)
        forms = (
            "a username shorthand or an explicit ID or URL reference"
            if family == "profile"
            else "a supported string shorthand or an explicit ID or URL reference"
        )
        return (
            f"    def {accessor_name(name)}(self, reference: str | None = None, *{keyword_parameters}) -> {node_class_name(child.path, sync=sync)}:\n"
            f'        """Select the {family} resource using {forms}.\n\n'
            f"        Resource selection is synchronous and does not perform a request.\n"
            f'        """\n'
            f'        identifier = resolve_selector(reference{keyword_arguments}, platform="{platform}", resource="{family}")\n'
            f'        return {node_class_name(child.path, sync=sync)}(self._transport, {{**self._bindings, "{child.scope["parameter"]}": identifier}})'
        )

    def operation_method(self, node: TreeNode, operation: dict[str, Any], *, sync: bool) -> str:
        prefix = "" if sync else "async "
        awaited = "" if sync else "await "
        if operation["operation"] == "fetch":
            return (
                f"    {prefix}def fetch(self, url: str, *, freshness: Freshness | None = None, {CONTROL_PARAMETERS}) -> Response[models.FetchResource]:\n"
                + self.docstring(operation, sync=sync)
                + "        if not url or not url.strip():\n"
                + '            raise TypeError("fetch(url) requires a non-empty social URL.")\n'
                + '        body: dict[str, Any] = {"url": url}\n'
                + "        if freshness is not None:\n"
                + '            body["freshness"] = freshness\n'
                + f'        result = {awaited}self._transport.request("{operation["method"]}", "{operation["api_path"]}", {{}}, {{}}, json_body=body, timeout=timeout, max_retries=max_retries)\n'
                + "        return self._transport.response(result)"
            )
        parameters = query_parameters(operation)
        signature = "".join(parameter_signature(parameter) for parameter in parameters)
        params_literal = ", ".join(f'"{parameter["name"]}": {parameter["python"]}' for parameter in parameters)
        data_type = f"models.{self.data_type(operation)}"
        page_type = "Page" if sync else "AsyncPage"
        method_name = operation["operation"]
        if operation["paginated"]:
            return (
                f"    {prefix}def {method_name}(self, *{signature}, {CONTROL_PARAMETERS}) -> {page_type}[{data_type}]:\n"
                + self.docstring(operation, sync=sync)
                + f"        params: dict[str, Any] = {{{params_literal}}}\n"
                + f'        result = {awaited}self._transport.request("{operation["method"]}", "{operation["api_path"]}", self._bindings, params, timeout=timeout, max_retries=max_retries)\n'
                + f'        return self._transport.page(result, "{operation["method"]}", "{operation["api_path"]}", self._bindings, params, timeout, max_retries)'
            )
        return (
            f"    {prefix}def {method_name}(self, *{signature}, {CONTROL_PARAMETERS}) -> Response[{data_type}]:\n"
            + self.docstring(operation, sync=sync)
            + f"        params: dict[str, Any] = {{{params_literal}}}\n"
            + f'        result = {awaited}self._transport.request("{operation["method"]}", "{operation["api_path"]}", self._bindings, params, timeout=timeout, max_retries=max_retries)\n'
            + "        return self._transport.response(result)"
        )

    def items_method(self, node: TreeNode, operation: dict[str, Any], *, sync: bool) -> str:
        parameters = query_parameters(operation)
        signature = "".join(parameter_signature(parameter) for parameter in parameters)
        arguments = ", ".join(f"{parameter['python']}={parameter['python']}" for parameter in parameters)
        arguments = f"{arguments}, " if arguments else ""
        data_type = f"models.{self.data_type(operation)}"
        method_name = operation["operation"]
        items_name = "items" if method_name == "list" else f"{method_name}_items"
        if sync:
            return (
                f"    def {items_name}(self, *{signature}, {CONTROL_PARAMETERS}) -> Iterator[{data_type}]:\n"
                f'        """Iterate items lazily across pages of {operation["path"]}, one request per page."""\n'
                f"        page: Page[{data_type}] | None = self.{method_name}({arguments}timeout=timeout, max_retries=max_retries)\n"
                "        while page is not None:\n"
                "            yield from page.data\n"
                "            page = page.next()"
            )
        return (
            f"    async def {items_name}(self, *{signature}, {CONTROL_PARAMETERS}) -> AsyncIterator[{data_type}]:\n"
            f'        """Iterate items lazily across pages of {operation["path"]}, one request per page."""\n'
            f"        page: AsyncPage[{data_type}] | None = await self.{method_name}({arguments}timeout=timeout, max_retries=max_retries)\n"
            "        while page is not None:\n"
            "            for item in page.data:\n"
            "                yield item\n"
            "            page = await page.next()"
        )

    def data_type(self, operation: dict[str, Any]) -> str:
        response = operation["definition"]["responses"]["200"]["content"]["application/json"]["schema"]
        data = self.find_property(response, "data")
        if data is None:
            raise SystemExit(f"generator: operation {operation['path']} has no data schema.")
        if operation["paginated"]:
            data = data.get("items")
            if data is None:
                raise SystemExit(f"generator: paginated operation {operation['path']} data is not an array.")
        if "$ref" not in data:
            raise SystemExit(f"generator: operation {operation['path']} data is not a component reference.")
        return reference_name(data["$ref"])

    def docstring(self, operation: dict[str, Any], *, sync: bool) -> str:
        definition = operation["definition"]
        lines = [definition.get("summary") or operation["path"]]
        description = definition.get("description")
        if description:
            lines += ["", description]
        example = self.example(operation, sync=sync)
        if example:
            lines += ["", "Example:", f"    {example}"]
        operation_id = definition.get("x-openhandle-operation")
        if isinstance(operation_id, str):
            lines += ["", f"See https://openhandle.dev/docs/api-reference/{operation_id.replace('.', '-')}"]
        escaped = [line.replace("\\", "\\\\").replace('"""', '\\"\\"\\"') for line in lines]
        body = "\n".join(f"        {line}".rstrip() for line in escaped[1:])
        return f'        """{escaped[0]}\n{body}\n        """\n' if body else f'        """{escaped[0]}"""\n'

    def example(self, operation: dict[str, Any], *, sync: bool) -> str:
        prefix = "await " if not sync else ""
        if operation["operation"] == "fetch":
            return f'{prefix}openhandle.fetch("https://www.instagram.com/openai/", freshness="24h")'
        example_values = operation["definition"].get("x-openhandle-test-data", {}).get("example", {}) or {}
        call = f"{prefix}openhandle"
        for segment in operation["scope"]:
            call += f".{accessor_name(segment['name'])}"
            parameter = segment.get("parameter")
            if parameter:
                call += f"({json.dumps(example_values.get(parameter, f'<{parameter}>'))})"
        options = []
        for parameter in query_parameters(operation):
            if not parameter["required"] and parameter["name"] != "freshness":
                continue
            value = parameter["example"]
            if value is None:
                value = example_values.get(parameter["name"], f"<{parameter['name']}>")
            options.append(f"{parameter['python']}={json.dumps(value)}")
        return f"{call}.{operation['operation']}({', '.join(options)})"


class TreeNode:
    def __init__(self, path: list[str], scope: dict[str, Any] | None = None) -> None:
        self.path = path
        self.scope = scope or {}
        self.children: dict[str, TreeNode] = {}
        self.operations: dict[str, dict[str, Any]] = {}


def operation_definitions(document: dict[str, Any]) -> list[dict[str, Any]]:
    result = []
    seen = set()
    for api_path, path_item in document.get("paths", {}).items():
        for method, definition in path_item.items():
            if method not in HTTP_METHODS:
                continue
            sdk = definition.get("x-openhandle-sdk")
            if (
                not isinstance(sdk, dict)
                or not isinstance(sdk.get("path"), str)
                or not isinstance(sdk.get("scope"), list)
                or sdk.get("operation") not in TERMINAL_OPERATIONS
            ):
                raise SystemExit(f"generator: {method.upper()} {api_path} has no valid x-openhandle-sdk mapping.")
            if sdk["path"] in seen:
                raise SystemExit(f"generator: duplicate SDK path {sdk['path']}.")
            seen.add(sdk["path"])
            result.append(
                {
                    "api_path": api_path,
                    "method": method,
                    "operation": sdk["operation"],
                    "paginated": sdk.get("paginated") is True,
                    "path": sdk["path"],
                    "scope": sdk["scope"],
                    "definition": definition,
                }
            )
    result.sort(key=lambda operation: operation["path"])
    return result


def query_parameters(operation: dict[str, Any]) -> list[dict[str, Any]]:
    parameters = []
    for parameter in operation["definition"].get("parameters", []):
        if parameter.get("in") != "query":
            continue
        schema = parameter.get("schema", {})
        if parameter["name"] == "freshness":
            annotation = "Freshness"
        elif "enum" in schema:
            annotation = (
                "Literal[" + ", ".join(json.dumps(value) for value in schema["enum"] if value is not None) + "]"
            )
        elif schema.get("format") == "date-time":
            annotation = "str | datetime"
        elif schema.get("type") == "integer":
            annotation = "int"
        elif schema.get("type") == "boolean":
            annotation = "bool"
        else:
            annotation = "str"
        parameters.append(
            {
                "name": parameter["name"],
                "python": snake_case(parameter["name"]),
                "required": parameter.get("required") is True,
                "annotation": annotation,
                "example": parameter.get("example", schema.get("default")),
            }
        )
    parameters.sort(key=lambda parameter: not parameter["required"])
    return parameters


def parameter_signature(parameter: dict[str, Any]) -> str:
    if parameter["required"]:
        return f", {parameter['python']}: {parameter['annotation']}"
    return f", {parameter['python']}: {parameter['annotation']} | None = None"


def ordered_schema_names(schemas: dict[str, Any]) -> list[str]:
    ordered: list[str] = []
    visiting: set[str] = set()

    def dependencies(name: str) -> list[str]:
        schema = schemas[name]
        if set(schema) == {"$ref"}:
            return []
        result = []
        for part in schema.get("allOf", []):
            if "$ref" in part:
                result.append(reference_name(part["$ref"]))
        return result

    def visit(name: str) -> None:
        if name in ordered:
            return
        if name in visiting:
            raise SystemExit(f"generator: schema inheritance cycle at {name}.")
        visiting.add(name)
        for dependency in dependencies(name):
            visit(dependency)
        visiting.remove(name)
        ordered.append(name)

    for name in sorted(schemas):
        visit(name)
    return ordered


def schema_is_object(schema: dict[str, Any]) -> bool:
    types = schema.get("type")
    types = types if isinstance(types, list) else [types] if types else []
    return "object" in types or "properties" in schema


def literal_value(value: Any) -> str:
    return json.dumps(value) if isinstance(value, str) else repr(value)


def reference_name(reference: str) -> str:
    return reference.rsplit("/", 1)[-1]


def node_class_name(path: list[str], *, sync: bool) -> str:
    name = "".join(pascal_case(segment) for segment in path) + "Resource"
    return name if sync else f"Async{name}"


def accessor_name(value: str) -> str:
    return snake_case(value)


def pascal_case(value: str) -> str:
    if value in INITIALISMS:
        return INITIALISMS[value]
    parts = re.split(r"[^A-Za-z0-9]+", value)
    result = "".join(part[:1].upper() + part[1:] for part in parts if part)
    for old, new in (("Id", "ID"), ("Url", "URL"), ("QrCode", "QRCode"), ("Oembed", "OEmbed"), ("Tiktok", "TikTok")):
        result = result.replace(old, new)
    return result


def snake_case(value: str) -> str:
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", value).lower().replace("-", "_")


def write_generated(relative_path: str, contents: str, *, check: bool) -> None:
    target = PACKAGE_ROOT / relative_path
    if check:
        if not target.exists():
            raise SystemExit(f"{relative_path} is missing. Run python scripts/generate.py.")
        if target.read_text() != contents:
            raise SystemExit(f"{relative_path} is stale. Run python scripts/generate.py.")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(contents)


if __name__ == "__main__":
    main()
